<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LanStash.Domain\LanStash.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LanStash.Tests" />
  </ItemGroup>
</Project>
